name: pipeline

on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4

      - name: Install Python dependencies
        working-directory: app
        run: pip install -r requirements-dev.txt

      - name: Run unit tests
        working-directory: app
        run: pytest
