name: pipeline

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  unit-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Python dependencies
        working-directory: app
        run: pip install -r requirements-dev.txt

      - name: Run unit tests
        working-directory: app
        run: pytest --cov --cov-report=html:coverage_report tests/

      - if: ${{matrix.python-version == '3.12' && matrix.os == 'ubuntu-latest'}}
        name: Create Badge
        run: echo "Create Badge"
